Vagrant.configure(2) do |config|
  config.vm.box = "quarkslab/debian-7.7-amd64"
  config.vm.box_version = "1.0.1"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 80, host: 8181
  config.vm.synced_folder "www", "/home/www"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL

end
